name: Docker Image CI

on:
  release:
    types: [published]

env:
  NAME: lichodev/fvl-angular

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Get repository"
        uses: actions/checkout@v3

      - name: "Get version"
        uses: battila7/get-version-action@v2.2.1
        id: version

      - name: "Build the Docker image"
        run: "docker build -t ${{ env.NAME }} -t ${{ env.NAME }}:${{ steps.version.outputs.version-without-v }} -t ${{ env.NAME }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor}} -t ${{ env.NAME }}:${{ steps.version.outputs.major }} ."

      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Push Docker images"
        run: "docker push -a ${{ env.NAME }}"
